[data]
git-tree-sha1 = "8dc7ae0cc84fc1262c75d7114a13a6aad20d990a"

    [[data.download]]
    sha256 = "96cc3c2267c20879acf739ff4a2bcc6a8c8e7c5985ed5e83bd4ba200e37fcc46"
    url = "https://github.com/nicomignoni/SolarFunctions.jl/releases/download/v0.1.0-pre-release/data.tar.gz"
